platform :ios, "13.0"
use_frameworks! :linkage => :static
install! "cocoapods", :warn_for_unused_master_specs_repo => false

target 'CombinePropertyWrapperExample' do
  pod "CombinePropertyWrapper", :path => ".."
end